### ISSUE TITLE
Chef server login page not accessible

### ISSUE THREAD

**Issue by rathna27** [Accenture/adop-platform-extension-chef#11]
When i am trying to access the chef server based on the URL available in the output console of the "Load_Platform_Extension" build job execution successfully, the following page gets displayed instead of chef login server page. 

Request you to help on this at the earliest, since many DevOps Academy training going on parallel in IDC .
![error](https://cloud.githubusercontent.com/assets/27403444/25016135/6b6ec63c-209c-11e7-8e42-9ac70c412f51.png)

**Comment by aliciasteen** [comment]
Hi,
This has been fixed in #12 
Thanks

**Comment by dsingh07** [comment]
@rathna27 When you get time, please can you try this again and confirm if this works for you? We can then close this issue.

**Comment by rathna27** [comment]
Yes, this issue is resolved. Now Chef login page is accessible and we are able to proceed further. Thanks.
