### ISSUE TITLE
chef pipeline execution fail in Integration test

### ISSUE THREAD

**Issue by rathna27** [Accenture/adop-platform-extension-chef#13]
Hi All,

Chef pipeline execution fails in Integration test with error related to “Docker run. Due to this, we are not able to continue with lab activity.

**Comment by nickdgriffin** [comment]
Hi,

Can this be moved over to https://github.com/Accenture/adop-cartridge-chef please?

Can you also provide the job output including the error once moved please?

Thanks,
Nick

**Comment by rathna27** [comment]
Yes, I have moved this issue to the said location also along with job output.
